Lady-Face:
  title: Thin-Faced Lady Face 
  image: assets/images/lady-face.jpg
  id: 100
  description: This beautiful piece of art was designed by our excellent designer, Desi G. Ner.
  excerpt: Our number one seller!
  quantity: 1
  price: 10
  weight: 1 lb
  size: 8.5" x 11"