carmel-leather-couch:
  title: Carmel Leather Couch 
  image: assets/images/carmel-leather-couch.jpg
  id: 100
  description: This beautiful piece of art that you can recline in was designed by our excellent designer, Desi G. Ner.
  excerpt: Our number one seller!
  quantity: 1
  price: 1000
  weight: 120 lb
  size: large